In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from keras.models import  load_model
import streamlit as st
import pickle
import datetime

In [2]:
model = load_model('ann_model.h5')

## Load the pickle file
with open('scaler.pkl', 'rb') as f:
    scaler = pickle.load(f)

with open('label_encoder_gender.pkl', 'rb') as f:
    label_encoder = pickle.load(f)  

with open('OneHotGeo.pkl', 'rb') as f:
    onehot_encoder = pickle.load(f)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [3]:
# Example input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [4]:
geo_encoded = onehot_encoder.transform([[input_data['Geography']]]).toarray()
geo_df = pd.DataFrame(geo_encoded, columns=onehot_encoder.get_feature_names_out(['Geography']))
geo_df

d:\Projects\ANN Projects\annprjs\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [11]:
df = pd.DataFrame([input_data])
df = pd.concat([geo_df, df.drop(['Geography'], axis=1)], axis=1)
df

,Geography_France,Geography_Germany,Geography_Spain,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,1.0,0.0,0.0,600,Male,40,3,60000,2,1,1,50000

In [12]:
## Gender Label Encoding
df['Gender'] = label_encoder.transform(df['Gender'])
df

,Geography_France,Geography_Germany,Geography_Spain,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,1.0,0.0,0.0,600,1,40,3,60000,2,1,1,50000

In [14]:
scaled_data = scaler.transform(df)
scaled_data

array([[ 1.00150113, -0.57946723, -0.57638802, -0.53598516,  0.91324755,
         0.10479359, -0.69539349, -0.25781119,  0.80843615,  0.64920267,
         0.97481699, -0.87683221]])

In [15]:
## model Prediction
prediction = model.predict(scaled_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step

In [17]:
prediction

array([[0.03124808]], dtype=float32)